# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [62]:
import numpy as np

2. Create a null vector of size 10 

In [63]:
null_vec=np.zeros(10)
null_vec

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [64]:
vec_value=np.arange(10,49)
vec_value

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

4. Find the shape of previous array in question 3

In [65]:
vec_value.shape

(39,)

5. Print the type of the previous array in question 3

In [66]:
vec_value.dtype

dtype('int32')

6. Print the numpy version and the configuration


In [67]:
print(np.__version__,np.show_config())

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
1.18.2 None


7. Print the dimension of the array in question 3


In [68]:
vec_value.ndim

1

8. Create a boolean array with all the True values

In [69]:
boolean_array=np.array(range(1,10),dtype="bool")
boolean_array

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

9. Create a two dimensional array




In [70]:
two_dimensional=np.ones((2,2))
two_dimensional

array([[1., 1.],
       [1., 1.]])

10. Create a three dimensional array



In [71]:
three_dimensional=np.zeros((3,3,3))
three_dimensional

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

11. Reverse a vector (first element becomes last)

In [72]:
reverse_vector=np.array(range(1,10))
print(reverse_vector)
reverse_vector[0],reverse_vector[len(reverse_vector)-1]=reverse_vector[len(reverse_vector)-1],reverse_vector[0]
print(reverse_vector)

[1 2 3 4 5 6 7 8 9]
[9 2 3 4 5 6 7 8 1]


12. Create a null vector of size 10 but the fifth value which is 1 

In [73]:
null_vec=np.zeros(10)
null_vec[5]=1
null_vec

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [74]:
idt_matrix=np.identity(3)
idt_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [75]:
arr=np.array([1,2,3,4,5])
arr=arr.astype(np.float32)

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [76]:
arr1=np.array([[1.,2.,3.],[4.,5.,6.]])
arr2=np.array([[0.,4.,1.],[7.,2.,12.]])
arr1*arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [77]:
np.greater(arr1,arr2)

array([[ True, False,  True],
       [False,  True, False]])

17. Extract all odd numbers from arr with values(0-9)

In [78]:
arr=np.arange(9)
#odd_values= filter(lambda val: val % 2 == 0, arr)
#list(odd_values)
arr[arr % 2==0]

array([0, 2, 4, 6, 8])

18. Replace all odd numbers to -1 from previous array

In [79]:
arr[arr % 2==0]=-1
arr

array([-1,  1, -1,  3, -1,  5, -1,  7, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [80]:
arr=np.arange(10)
arr[5]=arr[6]=arr[7]=arr[8]=12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [81]:
arr=np.ones((8,8))
arr[1:-1,1:-1]=0
arr

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [82]:
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])
arr2d[1,1]=12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [83]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0][:]=64
#arr3d[1][:]=64
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [84]:
arr=np.arange(9).reshape(3,3)
print(arr)
val=arr[0]
val

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([0, 1, 2])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [85]:
arr=np.arange(9).reshape(3,3)
print(arr)
val=arr[1][1]
val

[[0 1 2]
 [3 4 5]
 [6 7 8]]


4

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [86]:
arr=np.arange(9).reshape(3,3)
print(arr)
val=arr[0:-1,-1]
val

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([2, 5])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [87]:
arr=np.arange(100).reshape(10,10)
min1=np.amax(arr,axis=1)
val=max(min1)
val

99

In [88]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
#Find the common items between a and b
np.intersect1d(a,b)

array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [89]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a == b)

(array([1, 3, 5, 7], dtype=int64),)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [90]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
print(data)
print(np.where(names[data] != "will"))

[[-0.0918083   0.47956749 -2.06944259  0.89891982]
 [-0.1476981  -0.4807695  -0.92057554 -0.66310861]
 [-3.34396744 -1.16401515 -1.16149124 -0.45241034]
 [-1.28498703 -0.02877408 -1.44623815 -0.31074543]
 [-1.61333145 -0.27278477 -0.11556828  1.09258668]
 [ 0.1786534  -0.10793405 -0.78094348  1.69017577]
 [-0.70995768 -0.85080957  1.4534752  -0.43526412]]


IndexError: arrays used as indices must be of integer (or boolean) type

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [ ]:
arr=np.random.uniform(low=1.0, high=15.0, size=(5,3))
arr

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [ ]:
arrrr=np.random.uniform(low=1.0, high=16.0, size=(2,2,4))
arrrr

33. Swap axes of the array you created in Question 32

In [ ]:
np.swapaxes(arrrr, 0, 1)
arrrr

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [ ]:
import math
arr=np.arange(10)
arr=np.sqrt(arr)
arr=np.where(arr<0.5,0,arr)
arr

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [ ]:
arr1=np.random.randn(12)
arr2=np.random.randn(12)
arr3=np.maximum(arr1,arr2)
arr3

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [ ]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
unique=np.unique(names)
unique

In [ ]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
val=np.intersect1d(a,b)
a=filter(lambda x: x if x not in val else None,a)
np.asarray(list(a))

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [91]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
sampleArray[:, 1] = 10
sampleArray

array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [92]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [115]:
matrix = np.random.rand(4,5)
np.cumsum(matrix)

array([0.73902911, 1.67899137, 2.2735923 , 2.85930514, 3.6097269 ,
       3.84878083, 4.72234677, 4.75668012, 4.77872529, 5.18722134,
       5.19779547, 5.52368314, 6.38177401, 6.62990441, 7.31537798,
       7.95064868, 8.05711649, 8.49347314, 8.79833389, 8.80289302])