# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [9]:
import numpy as np
arr=np.arange(20)
arr=arr.reshape(2,len(arr) //2)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

# Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [10]:
arr1=np.array([[0,1,2,3,4],[5,6,7,8,9]])
arr2=np.array([[1,1,1,1,1],[1,1,1,1,1]])
np.vstack((arr1,arr2))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [14]:
arr1=np.array([[0,1,2,3,4],[5,6,7,8,9]])
arr2=np.array([[1,1,1,1,1],[1,1,1,1,1]])
np.hstack((arr1,arr2))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [16]:
array=np.array([[0,1,2,3,4],[5,6,7,8,9]])
array.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [9]:
import numpy as np
array=np.array([[[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14]]])
array=np.ravel(array)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [15]:
array=np.array([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14]).reshape(5,3)
array

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [25]:
arr=np.arange(25).reshape(5,5)
print("original:\n",arr)
print("square of array:\n", np.square(arr))

original:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
square of array:
 [[  0   1   4   9  16]
 [ 25  36  49  64  81]
 [100 121 144 169 196]
 [225 256 289 324 361]
 [400 441 484 529 576]]


## Question:8

### Create 5x6 an array and find the mean?

In [28]:
array=np.arange(30).reshape(5,6)
print("array:\n",array)
print("mean of array:\n",np.mean(array))


array:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
mean of array:
 14.5


## Question:9

### Find the standard deviation of the previous array in Q8?

In [32]:
print(array)
print("standard deviation:\n",np.std(array))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
standard deviation:
 8.65544144839919


## Question:10

### Find the median of the previous array in Q8?

In [34]:
print(array)
print("median:\n",np.median(array))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
median:
 14.5


## Question:11

### Find the transpose of the previous array in Q8?

In [36]:
print(array)
print("transpose:\n",np.transpose(array))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
transpose:
 [[ 0  6 12 18 24]
 [ 1  7 13 19 25]
 [ 2  8 14 20 26]
 [ 3  9 15 21 27]
 [ 4 10 16 22 28]
 [ 5 11 17 23 29]]


## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [41]:
array=np.arange(16).reshape(4,4)
print("array:\n",array)
print("diagonal:\n",np.trace(array))

array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
diagonal:
 30


## Question:13

### Find the determinant of the previous array in Q12?

In [45]:
array=np.linalg.det(array)
array

0.0

## Question:14

### Find the 5th and 95th percentile of an array?

In [47]:
arr=np.arange(100).reshape(10,10)
print("5th percentile:\n",np.percentile(arr,5))
print("95h percentile:\n",np.percentile(arr,95))

5th percentile:
 4.95
95h percentile:
 94.05


## Question:15

### How to find if a given array has any null values?

In [49]:
arr=np.arange(100).reshape(10,10)
arr=np.isnan(arr)
arr

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])